[tool.poetry]
name = "test-1"
version = "0.1.0"
description = ""
authors = ["MichaelSchlimme <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
ascii = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
